language: python
python:
  - "3.6"

install:
  - pip install mypy
  - pip install mypy_extensions

script:
  - python spec-checker/spec-checker.py specs/aead_chacha20poly1305.py
  - python spec-checker/spec-checker.py specs/chacha20.py
  - python spec-checker/spec-checker.py specs/poly1305.py
  - python spec-checker/spec-checker.py specs/sha2.py
  - cd specs
  - python aead_chacha20poly1305_test.py
  - python chacha20_test.py
  - python poly1305_test.py
  - python sha2_test.py
#  - mypy specs/aead_chacha20poly1305.py
#  - mypy specs/chacha20.py
#  - mypy specs/poly1305.py
#  - mypy specs/sha2.py
